version: '3'
services:
    mysql:
      build: ./Docker-Compose/mysql/
      volumes:
        # 初期データ
        - ./Docker-Compose/mysql/db:/init/docker-entrypoint-initdb.d
        # 永続化
        - ./Docker-Compose/mysql/db:/data/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=root

    phpmyadmin:
      image: phpmyadmin/phpmyadmin
      environment:
        - PMA_ARBITRARY=1
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      links: 
        - mysql
      ports:
        - 8080:80
      